##### Country of Interest #####
country: philippines
country_code: ph

##### Where is the data? #####
gisaid_fasta: data/gisaid_data/ncov_asia.fasta
gisaid_meta: data/gisaid_data/ncov_asia.tsv
gisaid_mask_file: resources/resources/mask.txt

redcap_mask_file: resources/resources/mask.txt
redcap_access: redcap_api_url_and_key.txt

output_path: output
previous_outputs: previous_outputs
publish_path: publish
export_path: publish/phylogenetics

##### Previous Outputs #####
previous_gisaid_lineages: previous_outputs/most_recent/previous_gisaid_lineages.csv
previous_redcap_lineages: previous_outputs/most_recent/previous_redcap_lineages.csv

##### global lineage definitions #####
global_lineages: dummy_files/global_lineages.txt

##### Filter thresholds #####
min_covg: 93
min_length: 29000

##### Mapping reference #####
reference_fasta: reference.fasta
reference_genbank_annotation: MN908947.gb

##### Trim coordinates #####
trim_start: 265
trim_end: 29674

##### Files of variants to search for #####
snps: resources/resources/snps.csv
dels: resources/resources/dels.csv

##### AA file #####
AAs: resources/resources/AAs.csv

##### File of lineages to split by #####
lineage_splits: resources/resources/lineage_splits.csv
lineage_aliases: resources/resources/alias_key.json

##### Outgroups #####
outgroups_metadata: resources/resources/gisaid_outgroups/gisaid_outgroups.metadata.tsv
outgroups_fasta: resources/resources/gisaid_outgroups/gisaid_outgroups.sequences.fasta

##### Guide tree #####
guide_tree: resources/resources/graft_guide.newick
test_guide_tree: resources/resources/test_guide_tree/test_guide_tree.tree

##### Date/Time #####
date:
time:
time_window: 99999

##### Working directory #####
cwd:

##### Json path #####
json_path: json

##### Webhooks to push to #####
webhook: webhook_url.txt
grapevine_webhook:
phylopipe_webhook:

##### report latex template #####
latex_template: resources/resources/latex_template.latex
